# Site settings
title: tech-nick-ly
name: "Nicholas Cronquist"
author: "Nicholas Cronquist"
email: nick@ncronquist.com
description: > # this means to ignore newlines until "baseurl:"
  [Hopefully] Useful posts about web development and other tech related materials.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://ncronquist.com" # the base hostname & protocol for your site
twitter_username: nicholaibee
github_username:  ncronquist

# Build settings
markdown: redcarpet
highligher: pygments
exclude: [README.md]
excerpt_separator: <!--more-->
